(function() {var implementors = {};
implementors['wayland_client'] = ["<a class='stability Stable' title='Stable'></a>impl&lt;S: <a class='trait' href='wayland_client/core/trait.Surface.html' title='wayland_client::core::Surface'>Surface</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='wayland_client/core/struct.ShellSurface.html' title='wayland_client::core::ShellSurface'>ShellSurface</a>&lt;S&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;'p, S: <a class='trait' href='wayland_client/core/trait.Surface.html' title='wayland_client::core::Surface'>Surface</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='wayland_client/core/struct.SubSurface.html' title='wayland_client::core::SubSurface'>SubSurface</a>&lt;'p, S&gt;",];implementors['image'] = ["<a class='stability Stable' title='Stable'></a>impl&lt;P, Container&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='image/struct.ImageBuffer.html' title='image::ImageBuffer'>ImageBuffer</a>&lt;P, Container&gt;",];implementors['glium'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='glutin/api/wayland/struct.WAYLAND_CONTEXT.html' title='glutin::api::wayland::WAYLAND_CONTEXT'>WAYLAND_CONTEXT</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='glutin/api/x11/struct.GLOBAL_XOPENIM_LOCK.html' title='glutin::api::x11::GLOBAL_XOPENIM_LOCK'>GLOBAL_XOPENIM_LOCK</a>","<a class='stability Stable' title='Stable'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='glium/backend/glutin_backend/struct.WinRef.html' title='glium::backend::glutin_backend::WinRef'>WinRef</a>&lt;'a&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;'a, T&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='glium/vertex/struct.Mapping.html' title='glium::vertex::Mapping'>Mapping</a>&lt;'a, T&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
